export * from "./SplashScreen";
export * from "./Home";
export * from "./New";
export * from "./User";
export * from "./LoadingScreen";
export * from "./Save";
export * from "./Class";
export * from "./Treatment";
export * from "./Slider"
export * from "./CameraScreen.js"
